#!/bin/bash

# --print_tasks=1 
#./Run_CO-UP model=Alex --order=BBBBBBBB push=1 compile=1
#./Run_CO-UP model=MobileV1 --order=NNNNNNNNNNNNNNNBGGGGGGGLLLLL --n=60 --threads=2 --threads2=4 --GPU_Host=B push=1 compile=1
#./Run_CO-UP model=YOLOv3 --order=BBBBBBBGGGGGBBBBBLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBLLLLLLLLLLLLLLLLLLLLLLGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG --n=3 --threads=2 --threads2=4 --GPU_Host=B push=1 compile=1
# when just conv:
#./Run_CO-UP model=YOLOv3 --order=BBBGGBBLLLLLLLLLLLLLLLLBBBBBBBBBBBBBBBBBBLLLLLLLLLGGGGGGGGGGGGGGGGGGGGGGGGG --n=3 --threads=2 --threads2=4 --GPU_Host=B push=1 compile=1
#NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
#BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBN
#BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBNNNNNNNNNN
#set -x
#if any command fails the script stops instead of continuing 
set -e


# Declare an associative array to store options and values
declare -A options
# Get the directory of the script
SCRIPT_DIR=$(cd $(dirname "$0") && pwd)

governor="governor_pandoon"
governor_path="$SCRIPT_DIR/utils/DVFS/${governor}.ko"  # Assign your new value to a variable

ab

adb push $governor_path /data/local/tmp/
#adb shell insmod /data/local/tmp/$governor
if adb shell lsmod | grep -wq "$governor"; then
    echo "Module is already inserted, removing and reinserting..."
    #adb shell rmmod "$governor"
else
adb shell insmod "/data/local/tmp/${governor}.ko"
fi
#adb shell lsmod

#file_path="utils/DVFS/DVFS.h"
#sed -i "s|static std::string governor_module=\"[^\"]*\"|static std::string governor_module=\"$x\"|" "$file_path"



# Loop through command-line arguments
for arg in "$@"; do
  # Check if the argument is in the form "option=value"
  if [[ "$arg" == *=* ]]; then
    # Extract option and value using parameter expansion
    option="${arg%%=*}"
    value="${arg#*=}"
    
    # Store the option and value in the associative array
    options["$option"]="$value"
  fi
done

# Print the contents of the options array
#for key in "${!options[@]}"; do
#  echo "Option: $key, Value: ${options[$key]}"
#done

adb shell 'echo userspace > /sys/devices/system/cpu/cpufreq/policy0/scaling_governor'
adb shell 'echo userspace > /sys/devices/system/cpu/cpufreq/policy4/scaling_governor'
adb shell 'echo 1416000 > /sys/devices/system/cpu/cpufreq/policy0/scaling_setspeed'
adb shell 'echo 1800000 > /sys/devices/system/cpu/cpufreq/policy4/scaling_setspeed'

adb shell 'echo userspace > /sys/class/devfreq/ff9a0000.gpu/governor'
#adb shell 'cat /sys/class/devfreq/ff9a0000.gpu/governor'
adb shell 'echo 800000000 > /sys/class/devfreq/ff9a0000.gpu/userspace/set_freq'

current_dir=$(pwd)
p="/data/data/com.termux/files/home/ARMCL-RockPi"
p="/data/local/ARM-CO-UP"
laptop_dir="/home/ehsan/UvA/ARMCL/Rock-Pi/ComputeLibrary_64"
laptop_dir="/home/ehsan/UvA/ARMCL/Rock-Pi/ComputeLibrary_64_Yolov3"
#_path="/data/data/com.termux/files/home/ARMCL-RockPi/"

_dt1="$p/assets/${S}/alexnet/"
_dt2="$p/assets/${S}/googlenet/"
_dt3="$p/assets/${S}/mobilenet/"
_dt4="$p/assets/${S}/resnet50/"
_dt5="$p/assets/${S}/squeezenet/"
_dt6="$p/assets/${S}/yolov3/"

_img1="$p/assets/${S}/ppm_images_227/"
_img2="$p/assets/${S}/ppm_images_224/"
_img3="$p/assets/${S}/ppm_images_608/"


_lbl="$p/assets/${S}/labels.txt"
_lbl_detection="$p/assets/${S}/coco.names"


lbl=""
img=""
dt=""

remaining_options=()
for key in "${!options[@]}"; do
  if [[ $key != "model" && $key != "push" && $key != "compile" ]]
  then
  	#echo "rem Option: $key, Value: ${options[$key]}"
  	remaining_options+=("$key=${options[$key]}")
  fi
done

if [ "$1" == "-h" ]
then
   echo "pushtest [1-binarygraph] [2-board push dir] [3-target] [4-image?] [5-data?] [6-labels?] [7-n] [8-save?] [9-annotate?] [10-partition_point] [11-partition_point2] [12-order] [13-layer_timing] [14-Big_threads] [15-little_threads] [16-Graph] [17-GPU_host] [18-NPU_host]" ;
   echo "data: 1-alexnet 2-googlenet 3-mobilenet 4-resnet50 5-squeezenet";
   exit; 
fi

v="${options[--order]}"
caching="NO"
caching="YES"

if ((0)); then
	start=`expr index "$v" N`
	start=$((start-1))
	count=$(awk -FN '{print NF-1}' <<<"$v")
	
	end=$((start+count-1))
	
	#start=$((start+1))
	#end=$((end+1))

	#echo $start
	#echo $end
	echo "Checking file: /home/ehsan/UvA/Sub_Model/${options[model]}/${options[model]}_${start}_${end}.rknn"
	echo "File exists: $( [ -f /home/ehsan/UvA/Sub_Model/${options[model]}/${options[model]}_${start}_${end}.rknn ] && echo yes || echo no )"
	echo "Caching value: $caching"
	if (( $count>0 )); then
		if [[ `adb shell ls $p/graphs/${options[model]}_${start}_${end}.rknn 2> /dev/null` ]] && [[ $caching == "YES" ]]; then 
			echo "file $p/graphs/${options[model]}_${start}_${end}.rknn exist on board";
		else
			#if [ ! -f /home/ehsan/UvA/ARMCL/Khadas/ARMCL-Local/scripts/blobs_extractor/Working_tree/Sub_Model/${16}/${16}_${start}_${end}.rknn ]; then
			if [[ ! -f /home/ehsan/UvA/Sub_Model/${options[model]}/${options[model]}_${start}_${end}.rknn ]] || [[ $caching == "NO" ]]; then
				#/home/ehsan/UvA/ARMCL/Khadas/ARMCL-Local/scripts/blobs_extractor/Working_tree/Sub_Model/a.out ${16} $start $end
				/home/ehsan/UvA/Sub_Model/CO-UP.out ${options[model]} $start $end
				sleep 2
			fi
			#adb -s DKORWVI0P0 push /home/ehsan/UvA/ARMCL/Khadas/ARMCL-Local/scripts/blobs_extractor/Working_tree/Sub_Model/${16}/${16}_${start}_${end}.rknn $p/graphs/${16}_${start}_${end}.rknn
			#adb -s DKORWVI0P0 push /home/ehsan/UvA/Sub_Model/${16}/${16}_${start}_${end}.rknn $p/graphs/${16}_${start}_${end}.rknn
			adb  push /home/ehsan/UvA/Sub_Model/${options[model]}/${options[model]}_${start}_${end}.rknn $p/graphs/${options[model]}_${start}_${end}.rknn
			sleep 5
		fi
	fi

fi


pos=0
while [[ $pos -lt ${#v} ]]; do
    # Find the start of an N substring
    if [[ ${v:$pos:1} == "N" ]]; then
        start=$pos

        # Find the end of this N substring
        while [[ ${v:$pos:1} == "N" && $pos -lt ${#v} ]]; do
            pos=$((pos+1))
        done
        end=$((pos-1))

		#start=$((start+1))
		#end=$((end+1))
        echo "start=$start, end=$end"
		
			if [[ `adb shell ls $p/graphs/${options[model]}_${start}_${end}.rknn 2> /dev/null` ]] && [[ $caching == "YES" ]]; then 
				echo "file $p/graphs/${options[model]}_${start}_${end}.rknn exist on board";
			else
				#if [ ! -f /home/ehsan/UvA/ARMCL/Khadas/ARMCL-Local/scripts/blobs_extractor/Working_tree/Sub_Model/${16}/${16}_${start}_${end}.rknn ]; then
				if [[ ! -f /home/ehsan/UvA/Sub_Model/${options[model]}/${options[model]}_${start}_${end}.rknn ]] || [[ $caching == "NO" ]]; then
					#/home/ehsan/UvA/ARMCL/Khadas/ARMCL-Local/scripts/blobs_extractor/Working_tree/Sub_Model/a.out ${16} $start $end
					/home/ehsan/UvA/Sub_Model/CO-UP.out ${options[model]} $start $end
					sleep 2
				fi
				#adb -s DKORWVI0P0 push /home/ehsan/UvA/ARMCL/Khadas/ARMCL-Local/scripts/blobs_extractor/Working_tree/Sub_Model/${16}/${16}_${start}_${end}.rknn $p/graphs/${16}_${start}_${end}.rknn
				#adb -s DKORWVI0P0 push /home/ehsan/UvA/Sub_Model/${16}/${16}_${start}_${end}.rknn $p/graphs/${16}_${start}_${end}.rknn
				adb  push /home/ehsan/UvA/Sub_Model/${options[model]}/${options[model]}_${start}_${end}.rknn $p/graphs/${options[model]}_${start}_${end}.rknn
				sleep 5
			fi
    else
        pos=$((pos+1))
    fi
done



case "${options[model]}" in
    "Alex" | "alex")
		lbl=$_lbl
		img=$_img1
		dt=$_dt1
		graph="graph_alexnet_pipeline"
        ;;
    "Google" | "google")
		lbl=$_lbl
		img=$_img2
		dt=$_dt2
		graph="graph_googlenet_pipeline"
        ;;
    "MobileV1" | "mobilev1")
		lbl=$_lbl
		img=$_img2
		dt=$_dt3
		graph="graph_mobilenet_pipeline"
        ;;
	"ResV1_50" | "res50")
		lbl=$_lbl
		img=$_img2
		dt=$_dt4
		graph="graph_resnet50_pipeline"
        ;;
	"SqueezeV1" | "squeeze")
		lbl=$_lbl
		img=$_img1
		dt=$_dt5
		graph="graph_squeezenet_pipeline"
        ;;
	"YOLOv3" | "yolo")
		lbl=$_lbl_detection
		img=$_img3
		dt=$_dt6
		graph="graph_yolov3_pipeline"
		
        ;;
    *)
        echo "Unknown fruit."
        ;;
esac

echo ${grpah}
#graph=graph_mobilenet
if [ "${options[compile]}" == "1" ]; then
    cd "${laptop_dir}"
    ./b64.sh 23
    cd "${current_dir}"
	#adb push ${laptop_dir}/build/examples/NPU/${graph} $p/test_graph/
    adb push "${laptop_dir}/build/examples/Pipeline/${graph}" "$p/test_graph/"
	#adb push "${laptop_dir}/build/examples/graph_mobilenet" "$p/test_graph/"
else
    if [ "${options[push]}" == "1" ]; then
		#adb push ${laptop_dir}/build/examples/NPU/${graph} $p/test_graph/
        adb push "${laptop_dir}/build/examples/Pipeline/${graph}" "$p/test_graph/"
    fi
fi

echo "#!/bin/bash" > ${SCRIPT_DIR}/run_command.sh
echo "adb shell $p/test_graph/${graph} --data=$dt --image=$img --labels=$lbl ""${remaining_options[@]}" >> ${SCRIPT_DIR}/run_command.sh
chmod +x ${SCRIPT_DIR}/run_command.sh
#adb shell $p/test_graph/${graph} --data=$dt --image=$img --labels=$lbl "${remaining_options[@]}"

