#compiler=arm-linux-androideabi-clang
#target=armv7a-linux-androideabi$1-clang
#p=/home/ehsan/UvA/ARMCL/android-ndk-r21e-linux-x86_64/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/
#cp $p/$target $p/$compiler

##XX=clang++ CC=clang scons Werror=0 -j16 debug=0 asserts=0 neon=1 opencl=1 os=android arch=armv7a 

#$compiler $2 -Iinclude/applib/ovxinc/include/ -Iinclude/service/ovx_inc/  -Llib/ -lovxlib -ljpeg_t -lvnn_inceptionv3 -Wl,-rpath,/system/usr/lib/

#rm $p/$compiler

import SCons
import os
#import subprocess
#import os.path

path='/home/ehsan/UvA/ARMCL/android-ndk-r21e-linux-x86_64/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin'
prefix = "arm-linux-androideabi-"
#ENV = {'PATH' : os.environ['PATH']}
#env = Environment(CPPPATH=['include/applib/ovxinc/include/','include/service/ovx_inc/'],CC=prefix+'clang',LIBS=['ovxlib','jpeg_t','vnn_inceptionv3'],ENV = {'PATH' : path}, LIBPATH=['lib/'],CCFLAGS=['-Wl'])
npu_env=Environment(CC=prefix+'clang',ENV = {'PATH' : os.environ['PATH']})
npu_env.Append(LINKFLAGS=[
    '-Wl,-rpath,/system/usr/lib/'
])
#,RPATH='/system/usr/lib/'
nn=npu_env.Program(target='out', source='main_all.c',LIBPATH=['lib/'],LIBS=['ovxlib','jpeg_t','vnn_inceptionv3'],CPPPATH=['include/applib/ovxinc/include/','include/service/ovx_inc/'])
AlwaysBuild(nn)
alias = npu_env.Alias('hey', nn)
Default(alias)

print("helooooooooooo\n")
